---
- name : Create Directory
  hosts: all
  vars :
          dir_path : /home/shyam/sample-dir/
  become: true
  tasks:
          - name: Create directory
            file:
                    path : "{{ dir_path  }}"
                    state : directory
                    mode : 0775
                    owner : shyam
                    group : shyam
                    recurse : yes
